version: "3.8"
services:
  phpcli:
    build:
      context: ./services/php
      args:
        PHP_RUNING: cli
        PHP_VERSION: php:${PHP_VERSION}-cli-alpine
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        PHP_EXTENSIONS: ${PHP_EXTENSIONS}
        TZ: "${TZ}"
    container_name: php-cli
    ports:
      - "${PHP_CLI_HOST_PORT}:80"
      - "${PHP_CLI_SSL_HOST_PORT}:443"
    volumes:
      - ${SOURCE_DIR}:/www/:rw
      - ${PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP_CONFD_DIR}:/usr/local/etc/php/conf.d/:rw
      - ${PHP_CLI_CONF_FILE}:/usr/local/etc/php/conf.d/php-cli.cnf:rw
      - ${PHP_CLI_LOG_DIR}:/var/log/php
      - ${DATA_DIR}/composer:/tmp/composer
    # restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - default
    tty: true
    command: php /www/webman/start.php start -d

  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - ${MYSQL_CONFD_DIR}:/etc/mysql/conf.d/:rw
      - ${MYSQL_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:rw
      - ${MYSQL_LOG_DIR}:/var/log/mysql:rw
      - ${DATA_DIR}/mysql:/var/lib/mysql/:rw
    restart: always
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      TZ: "${TZ}"

  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis
    ports:
      - "${REDIS_HOST_PORT}:6379"
    volumes:
      - ${REDIS_CONF_FILE}:/etc/redis.conf:ro
      - ${DATA_DIR}/redis:/data/:rw
    restart: always
    entrypoint: ["redis-server", "/etc/redis.conf"]
    environment:
      TZ: "${TZ}"
    networks:
      - default

networks:
  default:
